#!/usr/bin/env bash
#-*- coding: utf-8 -*-


PROJ_NAME=HelloWorld
if [ -n "$1" ];
then
	PROJ_NAME="$1"
fi

requirements=(node npm git)

for requirement in ${requirements[*]}
do
	which $requirement >/dev/null 2>&1
	if [ $? -ne 0 ];
	then
		echo $requirement should be installed
		exit 1
	fi
done

npms=(yo generator-code)

for p in ${npms[*]}
do
	npm ls -g $p || npm install -g $p
done

yo code\
	--extensionType command-ts\
	--extensionName $PROJ_NAME\
	--extensionDescription \
	--extensionDisplayName \

cd $PROJ_NAME >/dev/null 2>&1  && code .

